<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="controller/controller_dados_passagem.php" method="post">
    <input type="checkbox" name="assento1" value="1">
<input type="checkbox" name="assento2" value="2">
<input type="checkbox" name="assento3" value="3">
<input type="checkbox" name="assento4" value="4">
<input type="checkbox" name="assento5" value="5">
<input type="checkbox" name="assento6" value="6">
<input type="checkbox" name="assento7" value="7">
<input type="checkbox" name="assento8" value="8">
<input type="checkbox" name="assento9" value="9">
<input type="checkbox" name="assento10" value="10">
<input type="checkbox" name="assento11" value="11">
<input type="checkbox" name="assento12" value="12">
<input type="checkbox" name="assento13" value="13">
<input type="checkbox" name="assento14" value="14">
<input type="checkbox" name="assento15" value="15">
<input type="checkbox" name="assento16" value="16">
<input type="checkbox" name="assento17" value="17">
<input type="checkbox" name="assento18" value="18">
<input type="checkbox" name="assento19" value="19">
<input type="checkbox" name="assento20" value="20">
<input type="checkbox" name="assento21" value="21">
<input type="checkbox" name="assento22" value="22">
<input type="checkbox" name="assento23" value="23">
<input type="checkbox" name="assento24" value="24">
<input type="checkbox" name="assento25" value="25">
<input type="checkbox" name="assento26" value="26">
<input type="checkbox" name="assento27" value="27">
<input type="checkbox" name="assento28" value="28">
<input type="checkbox" name="assento29" value="29">
<input type="checkbox" name="assento30" value="30">
<input type="checkbox" name="assento31" value="31">
<input type="checkbox" name="assento32" value="32">
<input type="checkbox" name="assento33" value="33">
<input type="checkbox" name="assento34" value="34">
<input type="checkbox" name="assento35" value="35">
<input type="checkbox" name="assento36" value="36">
<input type="checkbox" name="assento37" value="37">
<input type="checkbox" name="assento38" value="38">
<input type="checkbox" name="assento39" value="39">
<input type="checkbox" name="assento40" value="40">
<input type="checkbox" name="assento41" value="41">
<input type="checkbox" name="assento42" value="42">
<input type="checkbox" name="assento43" value="43">
<input type="checkbox" name="assento44" value="44">
<input type="checkbox" name="assento45" value="45">
<input type="checkbox" name="assento46" value="46">
<input type="checkbox" name="assento47" value="47">
<input type="checkbox" name="assento48" value="48">
<input type="checkbox" name="assento49" value="49">
<input type="checkbox" name="assento50" value="50">
<input type="checkbox" name="assento51" value="51">
<input type="checkbox" name="assento52" value="52">
<input type="checkbox" name="assento53" value="53">
<input type="checkbox" name="assento54" value="54">
<input type="checkbox" name="assento55" value="55">
<input type="checkbox" name="assento56" value="56">
<input type="checkbox" name="assento57" value="57">
<input type="checkbox" name="assento58" value="58">
<input type="checkbox" name="assento59" value="59">
<input type="checkbox" name="assento60" value="60">
<input type="checkbox" name="assento61" value="61">
<input type="checkbox" name="assento62" value="62">
<input type="checkbox" name="assento63" value="63">
<input type="checkbox" name="assento64" value="64">
<input type="checkbox" name="assento65" value="65">
<input type="checkbox" name="assento66" value="66">
<input type="checkbox" name="assento67" value="67">
<input type="checkbox" name="assento68" value="68">
<input type="checkbox" name="assento69" value="69">
<input type="checkbox" name="assento70" value="70">
<input type="checkbox" name="assento71" value="71">
<input type="checkbox" name="assento72" value="72">
<input type="checkbox" name="assento73" value="73">
<input type="checkbox" name="assento74" value="74">
<input type="checkbox" name="assento75" value="75">
<input type="checkbox" name="assento76" value="76">
<input type="checkbox" name="assento77" value="77">
<input type="checkbox" name="assento78" value="78">
<input type="checkbox" name="assento79" value="79">
<input type="checkbox" name="assento80" value="80">
<input type="checkbox" name="assento81" value="81">
<input type="checkbox" name="assento82" value="82">
<input type="checkbox" name="assento83" value="83">
<input type="checkbox" name="assento84" value="84">
<input type="checkbox" name="assento85" value="85">
<input type="checkbox" name="assento86" value="86">
<input type="checkbox" name="assento87" value="87">
<input type="checkbox" name="assento88" value="88">
<input type="checkbox" name="assento89" value="89">
<input type="checkbox" name="assento90" value="90">
<input type="checkbox" name="assento91" value="91">
<input type="checkbox" name="assento92" value="92">
<input type="checkbox" name="assento93" value="93">
<input type="checkbox" name="assento94" value="94">
<input type="checkbox" name="assento95" value="95">
<input type="checkbox" name="assento96" value="96">
<input type="checkbox" name="assento97" value="97">
<input type="checkbox" name="assento98" value="98">
<input type="checkbox" name="assento99" value="99">
<input type="checkbox" name="assento100" value="100">
<input type="checkbox" name="assento101" value="101">
<input type="checkbox" name="assento102" value="102">
<input type="checkbox" name="assento103" value="103">
<input type="checkbox" name="assento104" value="104">
<input type="checkbox" name="assento105" value="105">
<input type="checkbox" name="assento106" value="106">
<input type="checkbox" name="assento107" value="107">
<input type="checkbox" name="assento108" value="108">
<input type="checkbox" name="assento109" value="109">
<input type="checkbox" name="assento110" value="110">
<input type="checkbox" name="assento111" value="111">
<input type="checkbox" name="assento112" value="112">
<input type="checkbox" name="assento113" value="113">
<input type="checkbox" name="assento114" value="114">
<input type="checkbox" name="assento115" value="115">
<input type="checkbox" name="assento116" value="116">
<input type="checkbox" name="assento117" value="117">
<input type="checkbox" name="assento118" value="118">
<input type="checkbox" name="assento119" value="119">
<input type="checkbox" name="assento120" value="120">
<input type="checkbox" name="assento121" value="121">
<input type="checkbox" name="assento122" value="122">
<input type="checkbox" name="assento123" value="123">
<input type="checkbox" name="assento124" value="124">
<input type="checkbox" name="assento125" value="125">
<input type="checkbox" name="assento126" value="126">
<input type="checkbox" name="assento127" value="127">
<input type="checkbox" name="assento128" value="128">
<input type="checkbox" name="assento129" value="129">
<input type="checkbox" name="assento130" value="130">
<input type="checkbox" name="assento131" value="131">
<input type="checkbox" name="assento132" value="132">
<input type="checkbox" name="assento133" value="133">
<input type="checkbox" name="assento134" value="134">
<input type="checkbox" name="assento135" value="135">
<input type="checkbox" name="assento136" value="136">
<input type="checkbox" name="assento137" value="137">
<input type="checkbox" name="assento138" value="138">
<input type="checkbox" name="assento139" value="139">
<input type="checkbox" name="assento140" value="140">
<input type="checkbox" name="assento141" value="141">
<input type="checkbox" name="assento142" value="142">
<input type="checkbox" name="assento143" value="143">
<input type="checkbox" name="assento144" value="144">
<input type="checkbox" name="assento145" value="145">
<input type="checkbox" name="assento146" value="146">
<input type="checkbox" name="assento147" value="147">
<input type="checkbox" name="assento148" value="148">
<input type="checkbox" name="assento149" value="149">
<input type="checkbox" name="assento150" value="150">
<input type="checkbox" name="assento151" value="151">
<input type="checkbox" name="assento152" value="152">
<input type="checkbox" name="assento153" value="153">
<input type="checkbox" name="assento154" value="154">
<input type="checkbox" name="assento155" value="155">
<input type="checkbox" name="assento156" value="156">
<input type="checkbox" name="assento157" value="157">
<input type="checkbox" name="assento158" value="158">
<input type="checkbox" name="assento159" value="159">
<input type="checkbox" name="assento160" value="160">
<input type="checkbox" name="assento161" value="161">
<input type="checkbox" name="assento162" value="162">
<input type="checkbox" name="assento163" value="163">
<input type="checkbox" name="assento164" value="164">
<input type="checkbox" name="assento165" value="165">
<input type="checkbox" name="assento166" value="166">
<input type="checkbox" name="assento167" value="167">
<input type="checkbox" name="assento168" value="168">
<input type="checkbox" name="assento169" value="169">
<input type="checkbox" name="assento170" value="170">
<input type="checkbox" name="assento171" value="171">
<input type="checkbox" name="assento172" value="172">
<input type="checkbox" name="assento173" value="173">
<input type="checkbox" name="assento174" value="174">
<input type="checkbox" name="assento175" value="175">
<input type="checkbox" name="assento176" value="176">
<input type="checkbox" name="assento177" value="177">
<input type="checkbox" name="assento178" value="178">
<input type="checkbox" name="assento179" value="179">
<input type="checkbox" name="assento180" value="180">
<input type="checkbox" name="assento181" value="181">
<input type="checkbox" name="assento182" value="182">
<input type="checkbox" name="assento183" value="183">
<input type="checkbox" name="assento184" value="184">
<input type="checkbox" name="assento185" value="185">
<input type="checkbox" name="assento186" value="186">
<input type="checkbox" name="assento187" value="187">
<input type="checkbox" name="assento188" value="188">
<input type="checkbox" name="assento189" value="189">
<input type="checkbox" name="assento190" value="190">
<input type="checkbox" name="assento191" value="191">
<input type="checkbox" name="assento192" value="192">
<input type="checkbox" name="assento193" value="193">
<input type="checkbox" name="assento194" value="194">
<input type="checkbox" name="assento195" value="195">
<input type="checkbox" name="assento196" value="196">
<input type="checkbox" name="assento197" value="197">
<input type="checkbox" name="assento198" value="198">
<input type="checkbox" name="assento199" value="199">
<input type="checkbox" name="assento200" value="200">

<input type="submit" value="enviar">
    </form>
</body>
</html>